-- #Table: Customer
--  #
-- #
-- #+-------------+---------+
-- #| Column Name | Type    |
-- #+-------------+---------+
-- #| customer_id | int     |
-- #| product_key | int     |
-- #+-------------+---------+
-- #product_key is a foreign key to Product table.
-- #
-- #
-- #
-- #
-- # Table: Product
--   #
-- #
-- #+-------------+---------+
-- #| Column Name | Type    |
-- #+-------------+---------+
-- #| product_key | int     |
-- #+-------------+---------+
-- #product_key is the primary key column for this table.
-- #
-- #
-- #
-- #
-- # Write an SQL query for a report that provides the customer ids from the Custom
-- #er table that bought all the products in the Product table.
-- #
-- # Return the result table in any order.
-- #
-- # The query result format is in the following example:
-- #
-- #
-- #
-- #
-- #Customer table:
--           #+-------------+-------------+
-- #| customer_id | product_key |
-- #+-------------+-------------+
-- #| 1           | 5           |
-- #| 2           | 6           |
-- #| 3           | 5           |
-- #| 3           | 6           |
-- #| 1           | 6           |
-- #+-------------+-------------+
-- #
-- #Product table:
--          #+-------------+
-- #| product_key |
-- #+-------------+
-- #| 5           |
-- #| 6           |
-- #+-------------+
-- #
-- #Result table:
--         #+-------------+
-- #| customer_id |
-- #+-------------+
-- #| 1           |
-- #| 3           |
-- #+-------------+
-- #The customers who bought all the products (5 and 6) are customers with id 1 and
-- # 3.
-- #
-- # 👍 113 👎 24
--
-- Runtime: 616 ms, faster than 18.36% of MySQL online submissions for Customers Who Bought All Products.
-- Memory Usage: 0B, less than 100.00% of MySQL online submissions for Customers Who Bought All Products.
--
-- #leetcode submit region begin(Prohibit modification and deletion)
SELECT customer_id
FROM customer
GROUP BY customer_id
HAVING COUNT(DISTINCT product_key) = (SELECT COUNT(*) FROM product)
-- #leetcode submit region end(Prohibit modification and deletion)
