-- #Table: Traffic
-- #
-- #
-- #+---------------+---------+
-- #| Column Name   | Type    |
-- #+---------------+---------+
-- #| user_id       | int     |
-- #| activity      | enum    |
-- #| activity_date | date    |
-- #+---------------+---------+
-- #There is no primary key for this table, it may have duplicate rows.
-- #The activity column is an ENUM type of ('login', 'logout', 'jobs', 'groups', 'h
-- #omepage').
-- #
-- #
-- #
-- #
-- # Write an SQL query that reports for every date within at most 90 days from tod
-- #ay, the number of users that logged in for the first time on that date. Assume t
-- #oday is 2019-06-30.
-- #
-- # The query result format is in the following example:
-- #
-- #
-- #Traffic table:
-- #+---------+----------+---------------+
-- #| user_id | activity | activity_date |
-- #+---------+----------+---------------+
-- #| 1       | login    | 2019-05-01    |
-- #| 1       | homepage | 2019-05-01    |
-- #| 1       | logout   | 2019-05-01    |
-- #| 2       | login    | 2019-06-21    |
-- #| 2       | logout   | 2019-06-21    |
-- #| 3       | login    | 2019-01-01    |
-- #| 3       | jobs     | 2019-01-01    |
-- #| 3       | logout   | 2019-01-01    |
-- #| 4       | login    | 2019-06-21    |
-- #| 4       | groups   | 2019-06-21    |
-- #| 4       | logout   | 2019-06-21    |
-- #| 5       | login    | 2019-03-01    |
-- #| 5       | logout   | 2019-03-01    |
-- #| 5       | login    | 2019-06-21    |
-- #| 5       | logout   | 2019-06-21    |
-- #+---------+----------+---------------+
-- #
-- #Result table:
-- #+------------+-------------+
-- #| login_date | user_count  |
-- #+------------+-------------+
-- #| 2019-05-01 | 1           |
-- #| 2019-06-21 | 2           |
-- #+------------+-------------+
-- #Note that we only care about dates with non zero user count.
-- #The user with id 5 first logged in on 2019-03-01 so he's not counted on 2019-06
-- #-21.
-- #
-- # 👍 66 👎 57
--
-- Runtime: 417 ms, faster than 83.85% of MySQL online submissions for New Users Daily Count.
-- Memory Usage: 0B, less than 100.00% of MySQL online submissions for New Users Daily Count.
--
-- #leetcode submit region begin(Prohibit modification and deletion)
-- # Write your MySQL query statement below
SELECT first_activity_date AS login_date, COUNT(*) AS user_count
FROM (SELECT MIN(activity_date) AS first_activity_date
      FROM traffic
      WHERE activity = 'login'
      GROUP BY user_id) first_activity
WHERE DATEDIFF('2019-06-30', first_activity_date) <= 90
GROUP BY login_date;
-- #leetcode submit region end(Prohibit modification and deletion)
