package com.leetcode.strings.easy;
//
// Given two strings s and t which consist of only lowercase letters.
//
// String t is generated by random shuffling string s and then add one more lett
// er at a random position.
//
// Find the letter that was added in t.
//
// Example:
//
// Input:
// s = "abcd"
// t = "abcde"
//
// Output:
// e
//
// Explanation:
// 'e' is the letter that was added.
// Related Topics Hash Table Bit Manipulation
// 👍 909 👎 292

// leetcode submit region begin(Prohibit modification and deletion)

public class FindTheDifference_389 {
  public char findTheDifference(String s, String t) {
    char result = 0;
    for (int i = 0; i < s.length(); i++) {
      result ^= s.charAt(i);
    }
    for (int i = 0; i < t.length(); i++) {
        result ^= t.charAt(i);
    }
    return result;
  }
}

/*
  O(n) Runtime: 1 ms, faster than 99.41% of Java online submissions for Find the Difference.
  O(1) Memory Usage: 38.1 MB, less than 41.16% of Java online submissions for Find the Difference.
 */

// leetcode submit region end(Prohibit modification and deletion)
